### ISSUE TITLE
Incorrect ISO country code for Great Britain

### ISSUE THREAD

**Issue by pheest** [Capgemini-Invent-France/CarbonAI#25]
The data/ademe_energy_mix_by_country.csv contains a lookup of country names.
The United Kingdom is listed there as Royaume-Uni,0.457,UK.

However, the ISO county code for Great Britain is actually GB (see https://en.wikipedia.org/wiki/ISO_3166-2:GB)

This causes a NameError to be raised in __get_energy_mix().

**Comment by Neyri** [comment]
Hi,
Thank you for reaching out.
This is indeed a mistake, feel free to create a pull request to fix this.
